/*
 * generated by Xtext 2.25.0
 */
package jbase.example.jbasescript.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import jbase.example.jbasescript.JbasescriptRuntimeModule;
import jbase.example.jbasescript.JbasescriptStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JbasescriptIdeSetup extends JbasescriptStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JbasescriptRuntimeModule(), new JbasescriptIdeModule()));
	}
	
}
