/*
 * generated by Xtext 2.25.0
 */
package jbase.example.jbasescript.ide;


/**
 * Use this class to register ide components.
 */
public class JbasescriptIdeModule extends AbstractJbasescriptIdeModule {
}
