/*
 * generated by Xtext 2.11.0.RC2
 */
package jbase.example.jbasescript.ide


/**
 * Use this class to register ide components.
 */
class JbasescriptIdeModule extends AbstractJbasescriptIdeModule {
}
