/*
 * generated by Xtext 2.11.0.RC2
 */
package jbase.testlanguage.ide


/**
 * Use this class to register ide components.
 */
class JbaseTestlanguageIdeModule extends AbstractJbaseTestlanguageIdeModule {
}
