/*
 * generated by Xtext 2.25.0
 */
package jbase.testlanguage.ide;


/**
 * Use this class to register ide components.
 */
public class JbaseTestlanguageIdeModule extends AbstractJbaseTestlanguageIdeModule {
}
