/*
 * generated by Xtext 2.25.0
 */
package jbase.testlanguage.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import jbase.testlanguage.JbaseTestlanguageRuntimeModule;
import jbase.testlanguage.JbaseTestlanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JbaseTestlanguageIdeSetup extends JbaseTestlanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JbaseTestlanguageRuntimeModule(), new JbaseTestlanguageIdeModule()));
	}
	
}
