/*
 * generated by Xtext
 */
package jbase.example.jbasescript

/** 
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
class JbasescriptStandaloneSetup extends JbasescriptStandaloneSetupGenerated {
	def static void doSetup() {
		new JbasescriptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
