/*
 * generated by Xtext 2.25.0
 */
package jbase.example.jbasescript;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JbasescriptStandaloneSetup extends JbasescriptStandaloneSetupGenerated {

	public static void doSetup() {
		new JbasescriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
