/*
 * generated by Xtext 2.25.0
 */
package jbase.example.jbasescript;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JbasescriptRuntimeModule extends AbstractJbasescriptRuntimeModule {
}
