/*
 * generated by Xtext
 */
package jbase.example.jbasescript;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JbasescriptStandaloneSetup extends JbasescriptStandaloneSetupGenerated{

	public static void doSetup() {
		new JbasescriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

