/*
 * generated by Xtext
 */
package jbase.example.jbasescript

/** 
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class JbasescriptRuntimeModule extends jbase.example.jbasescript.AbstractJbasescriptRuntimeModule {
}
