/*
 * generated by Xtext 2.25.0
 */
package jbase.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import jbase.JbaseRuntimeModule;
import jbase.JbaseStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JbaseIdeSetup extends JbaseStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JbaseRuntimeModule(), new JbaseIdeModule()));
	}
	
}
