/*
 * generated by Xtext
 */
package jbase.testlanguage.validation

import jbase.testlanguage.jbaseTestlanguage.AbstractOperation
import jbase.testlanguage.jbaseTestlanguage.JbaseTestLanguageModel
import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.xbase.XBlockExpression

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class JbaseTestlanguageValidator extends AbstractJbaseTestlanguageValidator {

	@Check
	def void checkReturnInOperation(AbstractOperation op) {
		checkMissingReturn(op.body as XBlockExpression)
	}

	@Check
	def void checkVariableInitializationInMainBlock(JbaseTestLanguageModel m) {
		checkVariableInitialization(m.block)
	}

	@Check
	def void checkVariableInitializationInOperation(AbstractOperation op) {
		checkVariableInitialization(op.body as XBlockExpression)
	}
}
