<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jbase" nsURI="http://www.Jbase.jbase" nsPrefix="jbase">
  <eClassifiers xsi:type="ecore:EClass" name="XJJvmFormalParameter" eSuperTypes="../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmFormalParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varArgs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XJAssignment" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XAssignment #//XJArrayAccess"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJVariableDeclaration" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XVariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalVariables" upperBound="-1"
        eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XVariableDeclaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XJAdditionalXVariableDeclaration" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XVariableDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJArrayAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XJArrayConstructorCall" eSuperTypes="#//XJArrayAccess ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        eType="#//XJArrayDimension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayLiteral" eType="#//XJArrayLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XJArrayDimension"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJArrayLiteral" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XListLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJArrayAccessExpression" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression #//XJArrayAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XJBranchingStatement" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJContinueStatement" eSuperTypes="#//XJBranchingStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJBreakStatement" eSuperTypes="#//XJBranchingStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJCharLiteral" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XStringLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJPrefixOperation" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XPostfixOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJConditionalExpression" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XIfExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJSwitchStatements" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XBlockExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJClassObject" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeExpression" eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayDimensions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XJSemicolonStatement" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression #//XJWithSemicolon">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XJTryWithResourcesStatement" eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XTryCatchFinallyExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openParenthesis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarationsBlock" eType="#//XJTryWithResourcesVariableDeclarations"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XJTryWithResourcesVariableDeclaration"
      eSuperTypes="#//XJVariableDeclaration #//XJWithSemicolon"/>
  <eClassifiers xsi:type="ecore:EClass" name="XJTryWithResourcesVariableDeclarations"
      eSuperTypes="../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XBlockExpression">
    <eOperations name="getResourceDeclarations">
      <eGenericType eClassifier="ecore:EDataType ../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//Iterable">
        <eTypeArguments eClassifier="#//XJTryWithResourcesVariableDeclaration"/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XJWithSemicolon" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semicolon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
