/*
 * generated by Xtext 2.25.0
 */
package jbase.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class JbaseQuickfixProvider extends DefaultQuickfixProvider {

}
