/*
 * generated by Xtext 2.10.0
 */
package jbase.testlanguage


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class JbaseTestlanguageRuntimeModule extends AbstractJbaseTestlanguageRuntimeModule {
}
