/*
 * generated by Xtext 2.10.0
 */
package jbase.testlanguage


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JbaseTestlanguageStandaloneSetup extends JbaseTestlanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new JbaseTestlanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
