/*
 * generated by Xtext
 */
package jbase.testlanguage;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class JbaseTestlanguageRuntimeModule extends jbase.testlanguage.AbstractJbaseTestlanguageRuntimeModule {

}
