/*
 * generated by Xtext 2.25.0
 */
package jbase.example.jbasescript.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JbasescriptUiModule extends AbstractJbasescriptUiModule {

	public JbasescriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
