/*
 * generated by Xtext
 */
package jbase.example.jbasescript.ui

import org.eclipse.ui.plugin.AbstractUIPlugin

/** 
 * Use this class to register components to be used within the IDE.
 */
class JbasescriptUiModule extends jbase.example.jbasescript.ui.AbstractJbasescriptUiModule {
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}
}
