/*
 * generated by Xtext
 */
package jbase.example.jbasescript.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JbasescriptUiModule extends jbase.example.jbasescript.ui.AbstractJbasescriptUiModule {
	public JbasescriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
