/*
 * generated by Xtext
 */
package jbase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.xbase.ui.DefaultXbaseUiModule;
import org.eclipse.xtext.xbase.ui.refactoring.ExtractVariableRefactoring;

import jbase.ui.refactoring.JbaseExtractVariableRefactoring;
import jbase.ui.syntaxcoloring.JbaseHighlightingConfiguration;
import jbase.ui.syntaxcoloring.JbaseTokenToAttributeIdMapper;

/**
 * This is meant to be used as the default base class for DSLs using Jbase.
 * 
 * @author Lorenzo Bettini
 */
public class DefaultJbaseUiModule extends DefaultXbaseUiModule {

	public DefaultJbaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return JbaseHighlightingConfiguration.class;
	}

	@Override
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return JbaseTokenToAttributeIdMapper.class;
	}

	public Class<? extends ExtractVariableRefactoring> bindExtractVariableRefactoring() {
		return JbaseExtractVariableRefactoring.class;
	}
}
