/*
 * generated by Xtext
 */
package jbase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import jbase.ui.syntaxcoloring.JbaseHighlightingConfiguration;
import jbase.ui.syntaxcoloring.JbaseTokenToAttributeIdMapper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JbaseUiModule extends jbase.ui.AbstractJbaseUiModule {
	public JbaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return JbaseHighlightingConfiguration.class;
	}

	@Override
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return JbaseTokenToAttributeIdMapper.class;
	}
}
