/**
 * generated by Xtext
 */
package jbase.ui;

import jbase.ui.refactoring.JbaseExtractVariableRefactoring;
import jbase.ui.syntaxcoloring.JbaseHighlightingConfiguration;
import jbase.ui.syntaxcoloring.JbaseTokenToAttributeIdMapper;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.xbase.ui.refactoring.ExtractVariableRefactoring;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JbaseUiModule extends AbstractJbaseUiModule {
	public JbaseUiModule(final AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return JbaseHighlightingConfiguration.class;
	}

	@Override
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return JbaseTokenToAttributeIdMapper.class;
	}

	public Class<? extends ExtractVariableRefactoring> bindExtractVariableRefactoring() {
		return JbaseExtractVariableRefactoring.class;
	}
}
