/**
 * generated by Xtext
 */
package jbase.testlanguage.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * See
 * https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class JbaseTestlanguageProposalProvider extends AbstractJbaseTestlanguageProposalProvider {
	/**
	 * You need to treat SpecialBlockExpression_Expressions as an XBlockExpression
	 * otherwise you won't get typical proposals that you'd get in a block; recall
	 * that SpecialBlockExpression_Expressions is defined as
	 * 
	 * <pre>
	 * SpecialBlockExpression returns xbase::XBlockExpression:
	 * {xbase::XBlockExpression}
	 * (expressions+=XJStatementOrBlock ';'*)*;
	 * </pre>
	 */
	@Override
	public void completeSpecialBlockExpression_Expressions(final EObject model, final Assignment assignment,
			final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
		completeWithinBlock(model, context, acceptor);
	}
}
