/*
 * generated by Xtext
 */
package jbase.example.purejbase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PureJbaseUiModule extends jbase.example.purejbase.ui.AbstractPureJbaseUiModule {
	public PureJbaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
