/*
 * generated by Xtext
 */
package jbase.example.jbasescript.ui.contentassist

import jbase.example.jbasescript.ui.contentassist.AbstractJbasescriptProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class JbasescriptProposalProvider extends AbstractJbasescriptProposalProvider {
}
