/*
 * generated by Xtext 2.10.0
 */
package jbase.example.jbasescript.tests

import com.google.inject.Inject
import jbase.example.jbasescript.jbasescript.JbasescriptLanguageModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(JbasescriptInjectorProvider)
class JbasescriptParsingTest{

	@Inject
	ParseHelper<JbasescriptLanguageModel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			System.out.println("Hello World!");
		''')
		Assert.assertNotNull(result)
	}

}
