/*
 * generated by Xtext 2.25.0
 */
package jbase.example.purejbase.ide;


/**
 * Use this class to register ide components.
 */
public class PureJbaseIdeModule extends AbstractPureJbaseIdeModule {
}
