/*
 * generated by Xtext 2.25.0
 */
package jbase.example.purejbase.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import jbase.example.purejbase.PureJbaseRuntimeModule;
import jbase.example.purejbase.PureJbaseStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PureJbaseIdeSetup extends PureJbaseStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PureJbaseRuntimeModule(), new PureJbaseIdeModule()));
	}
	
}
