/*
 * generated by Xtext
 */
package jbase.example.purejbase.ui.contentassist

import jbase.example.purejbase.ui.contentassist.AbstractPureJbaseProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class PureJbaseProposalProvider extends AbstractPureJbaseProposalProvider {
}
