/*
 * generated by Xtext 2.25.0
 */
package jbase.testlanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JbaseTestlanguageUiModule extends AbstractJbaseTestlanguageUiModule {

	public JbaseTestlanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
