/*
 * generated by Xtext
 */
package jbase.testlanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JbaseTestlanguageUiModule extends jbase.testlanguage.ui.AbstractJbaseTestlanguageUiModule {
	public JbaseTestlanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
