/*
 * generated by Xtext
 */
package jbase.example.purejbase;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PureJbaseRuntimeModule extends jbase.example.purejbase.AbstractPureJbaseRuntimeModule {

}
