/*
 * generated by Xtext 2.25.0
 */
package jbase.example.purejbase;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PureJbaseStandaloneSetup extends PureJbaseStandaloneSetupGenerated {

	public static void doSetup() {
		new PureJbaseStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
